"use client";

import { createTheme } from "@mui/material/styles";

export default createTheme({
  cssVariables: {
    cssVarPrefix: "",
    colorSchemeSelector: "data",
    disableCssColorScheme: true,
  },
  colorSchemes: {
    light: {
      palette: {
        common: {
          black: false,
          white: false,
          background: " ",
          onBackground: " ",
          backgroundChannel: " ",
          onBackgroundChannel: "",
        },
        primary: "",
        secondary: "",
        info: "",
        success: "",
        warning: "",
        error: "",
        text: "",
        background: {
          paper: "",
          default: "",
          paperChannel: "",
          defaultChannel: "",
        },
        grey: false,
        Alert: {
          warningColor: true,
          warningFilledBg: true,
          warningFilledColor: true,
          warningIconColor: true,
          warningStandardBg: true,
          errorColor: true,
          errorFilledBg: true,
          errorFilledColor: true,
          errorIconColor: true,
          errorStandardBg: true,
          infoColor: true,
          infoFilledBg: true,
          infoFilledColor: true,
          infoIconColor: true,
          infoStandardBg: true,
          successColor: true,
          successFilledBg: true,
          successFilledColor: true,
          successIconColor: true,
          successStandardBg: true,
        },
        Chip: {
          defaultAvatarColor: " ",
          defaultIconColor: " ",
          defaultBorder: " ",
        },
        Button: { inheritContainedBg: " ", inheritContainedHoverBg: " " },
        AppBar: { darkBg: true, defaultBg: true, darkColor: true },
        FilledInput: { disabledBg: " ", bg: " ", hoverBg: " " },
        Switch: { defaultColor: " ", defaultDisabledColor: " " },
        StepConnector: { border: " " },
        StepContent: { border: " " },
        Avatar: { defaultBg: true },
        Skeleton: { bg: " " },
        dividerChannel: " ",
        divider: " ",
        action: "",
      },
      opacity: {
        switchTrack: "",
        inputUnderline: "",
        inputPlaceholder: "",
        switchTrackDisabled: "",
      },
      overlays: [],
    },
    dark: {
      palette: {
        common: {
          black: false,
          white: false,
          background: " ",
          onBackground: " ",
          backgroundChannel: " ",
          onBackgroundChannel: " ",
        },
        primary: "",
        secondary: "",
        info: "",
        success: "",
        warning: "",
        error: "",
        text: "",
        background: {
          paper: "",
          default: "",
          paperChannel: "",
          defaultChannel: "",
        },
        grey: " ",
        Alert: {
          warningColor: true,
          warningFilledBg: true,
          warningFilledColor: true,
          warningIconColor: true,
          warningStandardBg: true,
          errorColor: true,
          errorFilledBg: true,
          errorFilledColor: true,
          errorIconColor: true,
          errorStandardBg: true,
          infoColor: true,
          infoFilledBg: true,
          infoFilledColor: true,
          infoIconColor: true,
          infoStandardBg: true,
          successColor: true,
          successFilledBg: true,
          successFilledColor: true,
          successIconColor: true,
          successStandardBg: true,
        },
        Chip: {
          defaultAvatarColor: " ",
          defaultIconColor: " ",
          defaultBorder: " ",
        },
        Button: { inheritContainedBg: " ", inheritContainedHoverBg: " " },
        AppBar: { darkBg: true, defaultBg: true, darkColor: true },
        FilledInput: { disabledBg: " ", bg: " ", hoverBg: " " },
        Switch: { defaultColor: " ", defaultDisabledColor: " " },
        StepConnector: { border: " " },
        StepContent: { border: " " },
        Avatar: { defaultBg: true },
        dividerChannel: " ",
        Skeleton: { bg: " " },
        Tooltip: { bg: " " },
        divider: " ",
        action: "",
      },
      opacity: {
        switchTrack: "",
        inputUnderline: "",
        inputPlaceholder: "",
        switchTrackDisabled: "",
      },
      overlays: [],
    },
  },
  typography: {
    h1: undefined,
    h2: undefined,
    h3: undefined,
    h4: undefined,
    h5: undefined,
    h6: undefined,
    subtitle1: undefined,
    subtitle2: undefined,
    body1: undefined,
    body2: undefined,
    caption: undefined,
    overline: undefined,
    button: undefined,
  },
  zIndex: "",
  spacing: "",
  shadows: [" "],
  shape: {
    borderRadius: "",
  },
  components: {
    MuiButtonBase: {
      styleOverrides: {
        root: {
          fontWeight: 700,
          borderRadius: 8,
          padding: "6px 12px",
          fontFamily: "inherit",
        },
      },
    },
    MuiCard: {
      defaultProps: {
        elevation: 0,
      },
    },
    MuiPaper: {
      defaultProps: {
        elevation: 0,
      },
    },
    MuiPopover: {
      defaultProps: {
        elevation: 0,
      },
    },
    MuiDrawer: {
      defaultProps: {
        elevation: 0,
      },
    },
    MuiDialog: {
      defaultProps: {
        PaperProps: {
          elevation: 0,
        },
      },
    },
    MuiMenu: {
      defaultProps: {
        elevation: 0,
      },
    },
  },
});
